### ISSUE TITLE
machine does not exist (the return)

### ISSUE THREAD

**Issue by hclhelio** [minishift/minishift#1268]
Hello!

I'm trying to test the minishift. But I'm capturing the same error I've seen reported on other tickets. Example [#1214](https://github.com/minishift/minishift/issues/1214)

* I'm using Windows 8.1
* VirtualBox 5.1.26 (I upgraded to this version by following a recommendation from the minishift website).
* Minishift version -> Minishift version: 1.4.1 with iso version 1.10 (https://github.com/minishift/minishift-b2d-iso/releases/download/v1.1.0/minishift-b2d.iso)
* Also tried with minishift version 1.0.0 and iso 1.0.0 (tag / v1.0.0).

Commands used:

```
C:\Users\myuser
λ minishift version
minishift v1.4.1+0f658ea

C:\Users\myuser
λ minishift delete
Deleting the Minishift VM...
Minishift VM deleted.

C:\Users\myuser
λ minishift start --vm-driver virtualbox --iso-url file://D:\nucleo\minishift-1.4.1-windows-amd64\minishift-b2d.iso --http-proxy http://MYUSER:mypassword@webpr
oxy.mycompany.com.br:XXXX --https-proxy https://myuser:mypassword@webproxy.mycompany.com.br:XXXX
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... \ FAI| E0815 10:31:15.897778    8336 start.go:342] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
.....
Error getting the state for host: machine does not exist
Error getting the state for host: machine does not exist
```

With 1.0.0:
```
C:\Users\myuser
λ minishift version
Minishift version: 1.0.0

C:\Users\myuser
λ minishift delete
Deleting the Minishift VM...
Minishift VM deleted.

C:\Users\myuser
λ minishift start --vm-driver virtualbox --iso-url file://D:\nucleo\minishift-1.0.0-windows-amd64\minishift-b2d.iso --http-proxy http://myuser:mypassword@webpr
oxy.mycompany.com.br:xxxx --https-proxy https://myuser:mypassword@webproxy.mycompany.com.br:xxxx
Starting local OpenShift cluster using 'virtualbox' hypervisor...
E0815 10:47:22.486851    7744 start.go:171] Error starting the VM: Error creating the VM. Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference
goroutine 26 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*StandardStack).Stack(0xe4cab0, 0xa24fc0, 0xc04200a0a0, 0xc04231b2f8)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:23 +0x29
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc.trapPanic(0xc04231ba78)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:129 +0xb4
panic(0xa24fc0, 0xc04200a0a0)
        /usr/local/go/src/runtime/panic.go:458 +0x251
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils.(*b2dReleaseGetter).download(0xc0423438d0, 0xc0423dc3c0, 0x20, 0xadf5e3, 0xf, 0xc04232c180, 0x3f, 0x0, 0x0)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils/b2d.go:198 +0x94
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils.(*B2dUtils).DownloadISO(0xc04238bf40, 0xc0423dc3c0, 0x20, 0xadf5e3, 0xf, 0xc04232c180, 0x3f, 0xc04238bf40, 0xc0421797d8)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils/b2d.go:357 +0x1b0
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils.(*B2dUtils).CopyIsoToMachineDir(0xc04238bf40, 0xc04232c180, 0x3f, 0xc04200b830, 0x9, 0x586104, 0xe2fe90)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils/b2d.go:461 +0x45f
github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox.(*b2dUtilsUpdater).CopyIsoToMachineDir(0xe4cab0, 0xc04200b840, 0xd, 0xc04200b830, 0x9, 0xc04232c180, 0x3f, 0xc0423163f0, 0xc0421799b8)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox/misc.go:27 +0x76
github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox.(*Driver).CreateVM(0xc0422e03c0, 0xc042179a58, 0x4501c0)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox/virtualbox.go:303 +0xb0
github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox.(*Driver).Create(0xc0422e03c0, 0xb3bf70, 0xc042179a88)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox/virtualbox.go:294 +0x36
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Create(0xc0420052e0, 0xe4cab0, 0xe4cab0, 0x0, 0x0)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:140 +0x7f
reflect.Value.call(0xc042014660, 0xc0420281d0, 0x13, 0xad5853, 0x4, 0xc04231bed0, 0x3, 0x3, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x5cf
reflect.Value.Call(0xc042014660, 0xc0420281d0, 0x13, 0xc04231bed0, 0x3, 0x3, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:302 +0xab
net/rpc.(*service).call(0xc042008c00, 0xc0421320c0, 0xc04200af80, 0xc04200d100, 0xc0420056e0, 0x9daa80, 0xe4cab0, 0x16, 0x9daa80, 0xe4cab0, ...)
        /usr/local/go/src/net/rpc/server.go:383 +0x14f
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:477 +0x428
. Retrying.
E0815 10:47:22.852095    7744 start.go:171] Error starting the VM: Error getting the state for host: machine does not exist. Retrying.
E0815 10:47:23.225546    7744 start.go:171] Error starting the VM: Error getting the state for host: machine does not exist. Retrying.
Error starting the VM:  Error creating the VM. Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference
goroutine 26 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*StandardStack).Stack(0xe4cab0, 0xa24fc0, 0xc04200a0a0, 0xc04231b2f8)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:23 +0x29
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc.trapPanic(0xc04231ba78)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:129 +0xb4
panic(0xa24fc0, 0xc04200a0a0)
        /usr/local/go/src/runtime/panic.go:458 +0x251
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils.(*b2dReleaseGetter).download(0xc0423438d0, 0xc0423dc3c0, 0x20, 0xadf5e3, 0xf, 0xc04232c180, 0x3f, 0x0, 0x0)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils/b2d.go:198 +0x94
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils.(*B2dUtils).DownloadISO(0xc04238bf40, 0xc0423dc3c0, 0x20, 0xadf5e3, 0xf, 0xc04232c180, 0x3f, 0xc04238bf40, 0xc0421797d8)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils/b2d.go:357 +0x1b0
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils.(*B2dUtils).CopyIsoToMachineDir(0xc04238bf40, 0xc04232c180, 0x3f, 0xc04200b830, 0x9, 0x586104, 0xe2fe90)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/mcnutils/b2d.go:461 +0x45f
github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox.(*b2dUtilsUpdater).CopyIsoToMachineDir(0xe4cab0, 0xc04200b840, 0xd, 0xc04200b830, 0x9, 0xc04232c180, 0x3f, 0xc0423163f0, 0xc0421799b8)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox/misc.go:27 +0x76
github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox.(*Driver).CreateVM(0xc0422e03c0, 0xc042179a58, 0x4501c0)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox/virtualbox.go:303 +0xb0
github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox.(*Driver).Create(0xc0422e03c0, 0xb3bf70, 0xc042179a88)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/virtualbox/virtualbox.go:294 +0x36
github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Create(0xc0420052e0, 0xe4cab0, 0xe4cab0, 0x0, 0x0)
        /Users/hardy/work/developer-platform/cdk-3/go/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:140 +0x7f
reflect.Value.call(0xc042014660, 0xc0420281d0, 0x13, 0xad5853, 0x4, 0xc04231bed0, 0x3, 0x3, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x5cf
reflect.Value.Call(0xc042014660, 0xc0420281d0, 0x13, 0xc04231bed0, 0x3, 0x3, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:302 +0xab
net/rpc.(*service).call(0xc042008c00, 0xc0421320c0, 0xc04200af80, 0xc04200d100, 0xc0420056e0, 0x9daa80, 0xe4cab0, 0x16, 0x9daa80, 0xe4cab0, ...)
        /usr/local/go/src/net/rpc/server.go:383 +0x14f
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:477 +0x428

Error getting the state for host: machine does not exist
Error getting the state for host: machine does not exist

C:\Users\myuser

```

I need to enable other feature in vbox to fix this problem?

Thank you very much,

**Comment by gbraad** [comment]
Please, do not use 1.0.0.

Can you specify file://D:\nucleo\minishift-1.4.1-windows-amd64\minishift-b2d.iso with forward slashes? but I would actually recommend:

```
C:\> minishift delete
C:\> minishift start --vm-driver virtualbox --iso-url b2d --http-proxy http://myuser:mypassword@webpr
oxy.mycompany.com.br:xxxx --https-proxy https://myuser:mypassword@webproxy.mycompany.com.br:xxxx
```

**Comment by budhrg** [comment]
@hclhelio I am also not sure why you need to specify `--iso-url` for default ISO, it will be automatically downloaded.
Technically you just need:
```
C:\> minishift start --vm-driver virtualbox --http-proxy http://myuser:mypassword@webpr
oxy.mycompany.com.br:xxxx --https-proxy https://myuser:mypassword@webproxy.mycompany.com.br:xxxx
```

**Comment by hclhelio** [comment]
@gbraad thanks for the suggested command.
I succeeded after resolving other proxy-related issues.

**Comment by gbraad** [comment]
Resolved

**Comment by hclhelio** [comment]
@budhrg I was specify --iso-url because in the first attempt the ISO was download with sucess. But in next install attempts, the proxy was returning erro related your cache.

In home, i can run with sucess  your command suggested.

Now, i'll try a new feature in openshift 3.6 (envs in jenkinsPipelineStrategy).

Thanks.

**Comment by gbraad** [comment]
I filed a related issue #1276 to disallow the backward slashes in the `--iso-url` option
