### ISSUE TITLE
Minishift VM cannot connect to the Internet

### ISSUE THREAD

**Issue by johnwp** [minishift/minishift#1352]
I'm wondering if this is a known issue. Minishift was working fine for a couple days when all of a sudden Openshift couldn't connect to my Gitlab repo. So I tried `minishift delete` and then `minishift start`. This is the output:

```
$ minishift start
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ...
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.0 image ...
   Pulling image openshift/origin:v3.6.0
FAIL
   Error: error pulling Docker image openshift/origin:v3.6.0
   Caused By:
     Error: Network timed out while trying to connect to https://index.docker.io/v1/repositories/openshift/origin/images. You may want to check your internet connection or if you are behind a proxy.
Error during 'cluster up' execution: Error starting the cluster.
```

**Comment by johnwp** [comment]
Never mind. Somehow my VPN was causing the connectivity issue, but I'm not sure why.

**Comment by gbraad** [comment]
VPN and VM is a known issue. Most of the VPN software does aggressive
routing, by forcing all packets over their route.

Which VPN did you use?

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by johnwp** [comment]
Thanks for the reply. I was using Tunnelblick.

**Comment by gbraad** [comment]
OpenVPN

**Comment by kev5** [comment]
Please help, I'm getting this problem-

C:\Users\keval\Downloads\minishift-1.12.0-windows-amd64>minishift start
-- Starting profile 'minishift'
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [===================================================================================] 100.00% 0s
-- Starting Minishift VM ............................................................................................. OK
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... FAIL
   VM is unable to ping external host
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... FAIL
   VM cannot connect to external URL with HTTP
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 0% used OK
-- Downloading OpenShift binary 'oc' version 'v3.6.1'
 33.97 MiB / 33.97 MiB [===================================================================================] 100.00% 0s-- Downloading OpenShift v3.6.1 checksums ... OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.1
-- Checking `oc` support for startup flags ...
   host-pv-dir ... OK
   host-volumes-dir ... OK
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
Starting OpenShift using openshift/origin:v3.6.1 ...
Pulling image openshift/origin:v3.6.1
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v3.6.1 image ...
   Pulling image openshift/origin:v3.6.1
FAIL
   Error: error pulling Docker image openshift/origin:v3.6.1
   Caused By:
     Error: Tag v3.6.1 not found in repository docker.io/openshift/origin
Error during 'cluster up' execution: Error starting the cluster.

**Comment by gbraad** [comment]
Several tests on startup fail, which indicate there is no outside
connectivity possible from the VM. Please check network settings.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by fulvi0** [comment]
Hi, I'm having a similar issue staring the minishift and I'm not using VPN

```bash
→ minishift --username fulvio@xxxx.com --password xxxxxxxx start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.9.0'
 40.44 MiB / 40.58 MiB [========================================================================================================================================================================]  99.66% 0s 
40.58 MiB / 40.58 MiB [========================================================================================================================================================================] 100.00% 0sOK
-- Checking if provided oc flags are supported ... OK
-- Starting local OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .................. OK
-- Registering machine using subscription-manager
   Registration in progress ...................................... FAIL [2m10.1s]
Error to register VM: ssh command error:
command : sudo -E subscription-manager register --auto-attach --username fulvio@xxxx.com --password ********
err     : exit status 70
output  : Registering to: subscription.rhsm.redhat.com:443/subscription
Network error, unable to connect to server. Please see /var/log/rhsm/rhsm.log for more information.
```

```bash
2018-07-03 22:59:35,292 [INFO] subscription-manager:1892:MainThread @connection.py:821 - Connection built: host=subscription.rhsm.redhat.com port=443 handler=/subscription auth=basic username=fulvio@xxxx.com
2018-07-03 22:59:36,328 [INFO] subscription-manager:1892:MainThread @dmiinfo.py:73 - Using dmidecode dump file: /dev/mem
2018-07-03 22:59:36,376 [INFO] subscription-manager:1892:MainThread @custom.py:85 - Loading custom facts from: /etc/rhsm/facts/cdk.facts
2018-07-03 23:01:43,686 [ERROR] subscription-manager:1892:MainThread @managercli.py:177 - Error during registration: [Errno 110] Connection timed out
2018-07-03 23:01:43,688 [ERROR] subscription-manager:1892:MainThread @managercli.py:178 - [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/subscription_manager/managercli.py", line 1184, in _do_command
    owner_key = self._determine_owner_key(admin_cp)
  File "/usr/lib/python2.7/site-packages/subscription_manager/managercli.py", line 1336, in _determine_owner_key
    owners = cp.getOwnerList(self.username)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 1117, in getOwnerList
    return self.conn.request_get(method)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 645, in request_get
    return self._request("GET", method, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 671, in _request
    info=info, headers=headers)
  File "/usr/lib64/python2.7/site-packages/rhsm/connection.py", line 527, in _request
    conn.request(request_type, handler, body=body, headers=final_headers)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1227, in connect
    HTTPConnection.connect(self)
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 110] Connection timed out
[docker@minishift ~]$
```
