### ISSUE TITLE
Cannot build image with the gradle docker plugin on the minishift docker

### ISSUE THREAD

**Issue by LeeWong** [minishift/minishift#1358]
Hi there,

I am having trouble to build, tag and push images with the gradle docker plugin:

[dockerjava-jaxrs-async-0] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.42.74:2376: Connection reset
[dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
org.apache.http.client.ClientProtocolException
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)

Here is the docker env:
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.42.74:2376"
export DOCKER_CERT_PATH="/home/lee/.minishift/certs"
export DOCKER_API_VERSION="1.24"

Here is the build configures:

    task buildImage(type: DockerBuildImage) {
        inputDir = projectDir
        tag = "${dockerOrg}/${project.name}:${commit}"
        doLast {
            println "Executing buildimage for $projectDir commit ${commit}"
        }
    }
    buildImage.dependsOn {
        tasks.findAll { task -> task.name.startsWith('pack') }
    }

    task tagImage(type: DockerTagImage) {
        dependsOn buildImage
        force = true
        imageId = buildImage.getTag()
        repository = "${dockerRegistry}/${dockerOrg}/${project.name}"
        tag = commit
        doLast {
            println "Executing tagImage for $projectDir commit ${commit}"
        }
    }

    task pushImage(type: DockerPushImage) {
        dependsOn tagImage
        tag = commit
        imageName = "${dockerRegistry}/${dockerOrg}/${project.name}"
        doLast {
            println "Executing pushImage for $projectDir commit ${commit}"
        }
    }
Thank you.

CHeers,
Lee

**Comment by LeeWong** [comment]
It has be resolved at https://github.com/EnMasseProject/enmasse/issues/193
