### ISSUE TITLE
Supported hypervisor check for a platform needs to happen before preflight

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift#1606]
On Linux I did the following

```
$ minishift start --vm-driver virtualbox --profile test2
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'
 0 B / 40.00 MiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%^C
$ minishift start --vm-driver hyperv --profile test2
-- Checking if Hyper-V driver is installed ... panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9b8e85]

goroutine 1 [running]:
github.com/minishift/minishift/pkg/minishift/shell/powershell.(*PowerShell).Execute(0xc420114f00, 0xb4dfca, 0x20, 0xc42029c0f0, 0xb46fe5, 0x18, 0x0)
        /var/workspaces/minishift/src/github.com/minishift/minishift/pkg/minishift/shell/powershell/powershell.go:34 +0x25
github.com/minishift/minishift/cmd/minishift/cmd.checkHypervDriverInstalled(0xb46fe5)
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:304 +0x48
github.com/minishift/minishift/cmd/minishift/cmd.preflightCheckSucceedsOrFails(0xb46d75, 0x18, 0xb6c628, 0xb538ba, 0x27, 0x0, 0xb46fe5, 0x18, 0xb606d7, 0x42)
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:154 +0x141
github.com/minishift/minishift/cmd/minishift/cmd.preflightChecksBeforeStartingHost()
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:80 +0x14f
github.com/minishift/minishift/cmd/minishift/cmd.runStart(0xc4202fc000, 0xc420124840, 0x0, 0x4)
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/cmd/start.go:161 +0x306
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202fc000, 0xc4201247c0, 0x4, 0x4, 0xc4202fc000, 0xc4201247c0)
        /var/workspaces/minishift/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:651 +0x23a
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1075f00, 0x0, 0x2, 0xc420112b70)
        /var/workspaces/minishift/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).Execute(0x1075f00, 0xc4201f5f68, 0x9d1f82)
        /var/workspaces/minishift/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/minishift/minishift/cmd/minishift/cmd.Execute()
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/cmd/root.go:139 +0x2d
main.main()
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/main.go:26 +0x25
```

Linux will never be able to support xhyve or hyperv... this validations happens as part of the `startHost`. This needs to happen earlier.

**Comment by gbraad** [comment]
this is related to validations not being consistently implemented, as the vm-driver is enforced on `m config set vm-driver` and on the actual `m start` code. This can also be seen in the `m start --help`.
