### ISSUE TITLE
Minishift stop often fails with Xhyve driver

### ISSUE THREAD

**Issue by agajdosi** [minishift/minishift#2682]
Integration tests on Mac often fails on `minishift stop`. Similar behaviour was reported in #2067.
I am able to reproduce only if I follow the steps which are part of basic.feature.

### General information

  * OS: macOS
  * Hypervisor: xhyve

### Steps to reproduce

  1. run basic.feature

### Logs

Steps executed before the stop:
```
minishift start
minishift oc-env
export PATH="/Users/hudson/.minishift/cache/oc/v3.9.30/darwin:$PATH"

oc get clusterrolebindings
oc get clusterrolebindings
oc --as system:admin get clusterrolebindings
oc config current-context
oc config set-context dummy
oc config use-context dummy
oc project -q
oc config use-context minishift
oc config current-context
oc --as system:admin get pv -o=name
oc login --username=developer --password=developer
oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git
oc expose svc/ruby-ex
oc set probe dc/ruby-ex --readiness --get-url=http://:8080
ruby-ex" rollout successfully within "1200
oc delete project ruby
oc logout
minishift image export alpine:latest
minishift stop --show-libmachine-logs -v 5
```
And here is the stop:
```
bash-3.2$ minishift stop --show-libmachine-logs -v 5
-- minishift version: v1.20.0+ddf020b
Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
Plugin server listening at address 127.0.0.1:55582
() DBG | operation not supported by device
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
Stopping the OpenShift cluster...
(minishift) Calling .DriverName
Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
Plugin server listening at address 127.0.0.1:55586
() DBG | operation not supported by device
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/hudson/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.64.5 -o IdentitiesOnly=yes -i /Users/hudson/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
sudo cat /etc/os-release
SSH cmd err, output: <nil>: NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
VARIANT="minishift"
VARIANT_VERSION="1.12.0"
BUILD_ID="cf9f525-08082018233334-503"

Couldn't set key CPE_NAME, no corresponding struct field found
Couldn't set key , no corresponding struct field found
Couldn't set key REDHAT_BUGZILLA_PRODUCT, no corresponding struct field found
Couldn't set key REDHAT_BUGZILLA_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key VARIANT_VERSION, no corresponding struct field found
Couldn't set key BUILD_ID, no corresponding struct field found
Detecting whether virtual machine is managed by a registration manager...
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/hudson/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.64.5 -o IdentitiesOnly=yes -i /Users/hudson/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
sudo -E subscription-manager
SSH cmd err, output: <nil>: Usage: subscription-manager MODULE-NAME [MODULE-OPTIONS] [--help]

Primary Modules: 

  attach         Attach a specified subscription to the registered system
  list           List subscription and product information for this system
  refresh        Pull the latest subscription data from the server
  register       Register this system to the Customer Portal or another subscription management service
  release        Configure which operating system release to use
  remove         Remove all or specific subscriptions from this system
  status         Show status information for this system's subscriptions and products
  unregister     Unregister this system from the Customer Portal or another subscription management service

Other Modules:   

  auto-attach    Set if subscriptions are attached on a schedule (default of daily)
  clean          Remove all local system and subscription data without affecting the server
  config         List, set, or remove the configuration parameters in use by this system
  environments   Display the environments available for a user
  facts          View or update the detected system information
  identity       Display the identity certificate for this system or request a new one
  import         Import certificates which were provided outside of the tool
  orgs           Display the organizations against which a user can register a system
  plugins        View and configure with 'subscription-manager plugins'
  redeem         Attempt to redeem a subscription for a preconfigured system
  repo-override  Manage custom content repository settings
  repos          List the repositories which this system is entitled to use
  service-level  Manage service levels for this system
  subscribe      Deprecated, see attach
  unsubscribe    Deprecated, see remove
  version        Print version information


found compatible host
Unregistering machine
(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/hudson/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.64.5 -o IdentitiesOnly=yes -i /Users/hudson/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
sudo -E subscription-manager version
SSH cmd err, output: <nil>: server type: Red Hat Subscription Management
subscription management server: 2.3.9-1
subscription management rules: 5.26
subscription-manager: 1.20.11-1.el7_5

(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/hudson/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.64.5 -o IdentitiesOnly=yes -i /Users/hudson/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
sudo -E subscription-manager unregister
SSH cmd err, output: <nil>: Unregistering from: subscription.rhsm.redhat.com:443/subscription
System has been unregistered.

(minishift) Calling .GetSSHHostname
(minishift) Calling .GetSSHPort
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHKeyPath
(minishift) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/hudson/.minishift/machines/minishift/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.64.5 -o IdentitiesOnly=yes -i /Users/hudson/.minishift/machines/minishift/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
sudo -E subscription-manager clean
SSH cmd err, output: <nil>: All local data removed

Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
Plugin server listening at address 127.0.0.1:55595
() DBG | operation not supported by device
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
Stopping "minishift"...
(minishift) Calling .GetState
(minishift) Calling .Stop
(minishift) Stopping minishift ...
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x43942a9]
(minishift) DBG | 
(minishift) DBG | goroutine 10 [running]:
(minishift) DBG | github.com/zchee/docker-machine-driver-xhyve/xhyve.(*Driver).GetState(0xc42014e0f0, 0x1, 0x0, 0x0)
(minishift) DBG | 	/Users/travis/gopath/src/github.com/zchee/docker-machine-driver-xhyve/xhyve/xhyve.go:338 +0xc9
(minishift) DBG | github.com/zchee/docker-machine-driver-xhyve/xhyve.(*Driver).Stop(0xc42014e0f0, 0x0, 0x0)
(minishift) DBG | 	/Users/travis/gopath/src/github.com/zchee/docker-machine-driver-xhyve/xhyve/xhyve.go:530 +0x125
(minishift) DBG | github.com/zchee/docker-machine-driver-xhyve/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Stop(0xc42011cca0, 0x4b09a18, 0x4b09a18, 0x0, 0x0)
(minishift) DBG | 	/Users/travis/gopath/src/github.com/zchee/docker-machine-driver-xhyve/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:221 +0x36
(minishift) DBG | reflect.Value.call(0xc4201302a0, 0xc420128220, 0x13, 0x45b891d, 0x4, 0xc420033f20, 0x3, 0x3, 0x2, 0x400f2a4, ...)
(minishift) DBG | 	/Users/travis/.gimme/versions/go1.8.1.darwin.amd64/src/reflect/value.go:434 +0x91f
(minishift) DBG | reflect.Value.Call(0xc4201302a0, 0xc420128220, 0x13, 0xc420021720, 0x3, 0x3, 0xc420021718, 0x403df11, 0xc420001520)
(minishift) DBG | 	/Users/travis/.gimme/versions/go1.8.1.darwin.amd64/src/reflect/value.go:302 +0xa4
(minishift) DBG | net/rpc.(*service).call(0xc42011e8c0, 0xc42011e0c0, 0xc4200101e0, 0xc420125b80, 0xc42000c360, 0x4514a80, 0x4b09a18, 0x16, 0x4514a80, 0x4b09a18, ...)
(minishift) DBG | 	/Users/travis/.gimme/versions/go1.8.1.darwin.amd64/src/net/rpc/server.go:387 +0x144
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG | 	/Users/travis/.gimme/versions/go1.8.1.darwin.amd64/src/net/rpc/server.go:481 +0x404
Error stopping cluster: unexpected EOF
```

**Comment by gbraad** [comment]
This is very likely related to an issue with the driver and system updates. Usually when EOF were noticed, it was related to a permission error; files were still locked.

**Comment by agajdosi** [comment]
@gbraad Cleaned .kube, .minishift folders, installed all updates, restarted the computer, having latest xhyve driver, but issue still persist. :cry:

**Comment by gbraad** [comment]
This permission issue is consistent, right. It is not related to the shutdown/stop procress of the driver...

**Comment by LalatenduMohanty** [comment]
@agajdosi Is your macOS is updated with latest updates?

**Comment by agajdosi** [comment]
@LalatenduMohanty Yes, it was updated 9 days ago + cleaned .kube, .minishift, checked xhyve version... nothing helped really.
