### ISSUE TITLE
can't start minishift during pre-create check: wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by klauern** [minishift/minishift#2799]
### General information

  * Minishift version: `v1.24.0+8a904d0`
  * OS: Windows
  * Hypervisor: Hyper-V

### Steps to reproduce

  1. `minishift stop; minishift delete; minishift profile set testing`
  2. `minishift start`

### Logs

```
C:\Users\266891\dev\docker\minishift
λ  minishift profile set testing
Profile 'testing' set as active profile.
C:\Users\266891\dev\docker\minishift
λ  minishift version
minishift v1.24.0+8a904d0
C:\Users\266891\dev\docker\minishift
λ  minishift start --show-libmachine-logs -v5
-- minishift version: v1.24.0+8a904d0
-- Starting profile 'testing'
-- Using proxy for the setup
        Using http proxy: http://user:pass@place:port
        Using https proxy: http://user:pass@place:port
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.10.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.10.0' is supported ... OK
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ...
   'Default Switch' ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    4 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....Found binary path at C:\Users\266891\scoop\apps\minishift\current\minishift.exe
Launching plugin server for driver hyperv
Plugin server listening at address 127.0.0.1:2347
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(testing) Calling .GetMachineName
(testing) Calling .DriverName
Creating CA: C:\Users\266891\.minishift\profiles\testing\certs\ca.pem
Creating client certificate: C:\Users\266891\.minishift\profiles\testing\certs\cert.pem
Running pre-create checks...
(testing) Calling .PreCreateCheck
(testing) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Module -ListAvailable hyper-v).Name | Get-Unique
..(testing) DBG | [stdout =====>] :
(testing) DBG | [stderr =====>] :
(testing) DBG | panic: runtime error: index out of range
(testing) DBG |
(testing) DBG | goroutine 36 [running]:
(testing) DBG | github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/hyperv.hypervAvailable(0xc042162201, 0x0)
(testing) DBG |         /home/minishift_ci/gopath/src/github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/hyperv/powershell.go:64 +0x10b
(testing) DBG | github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/hyperv.(*Driver).PreCreateCheck(0xc0423659e0, 0xc0422e00e0, 0xc0422e0100)
(testing) DBG |         /home/minishift_ci/gopath/src/github.com/minishift/minishift/vendor/github.com/docker/machine/drivers/hyperv/hyperv.go:168 +0x3d
(testing) DBG | github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).PreCreateCheck(0xc0424f6240, 0x1491390, 0x1491390, 0x0, 0x0)
(testing) DBG |         /home/minishift_ci/gopath/src/github.com/minishift/minishift/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:201 +0x3a
(testing) DBG | reflect.Value.call(0xc042365a40, 0xc042174840, 0x13, 0xdd65f4, 0x4, 0xc0424fff18, 0x3, 0x3, 0xc04205c040, 0x0, ...)
(testing) DBG |         /usr/lib/golang/src/reflect/value.go:447 +0x970
(testing) DBG | reflect.Value.Call(0xc042365a40, 0xc042174840, 0x13, 0xc0424fff18, 0x3, 0x3, 0x0, 0x0, 0x0)
(testing) DBG |         /usr/lib/golang/src/reflect/value.go:308 +0xab
(testing) DBG | net/rpc.(*service).call(0xc04216d540, 0xc0421600a0, 0xc0423bc238, 0xc0423bc280, 0xc042437f80, 0xc04217a460, 0xc4ef60, 0x1491390, 0x16, 0xc4ef60, ...)
(testing) DBG |         /usr/lib/golang/src/net/rpc/server.go:384 +0x155
(testing) DBG | created by net/rpc.(*Server).ServeCodec
(testing) DBG |         /usr/lib/golang/src/net/rpc/server.go:480 +0x441
.Wrapper Docker Machine process exiting due to closed plugin server (connection is shut down)
 FAIL E0913 12:55:48.716766   11836 start.go:437] Error starting the VM: Error creating the VM. Error with pre-create check: "read tcp 127.0.0.1:2348->127.0.0.1:2347: wsarecv: An existing connection was forcibly closed by the remote host.". Retrying.
Error starting the VM: Error creating the VM. Error with pre-create check: "read tcp 127.0.0.1:2348->127.0.0.1:2347: wsarecv: An existing connection was forcibly closed by the remote host."
C:\Users\266891\dev\docker\minishift
λ
```

**Comment by gbraad** [comment]
Are you sure you have installed the HyperV components?

It seems to fail on the docker/machine library.

Can you try to be xecute the following in PowerShell;

```
Get-Module -ListAvailable hyper-v
```

And let us know the results
