### ISSUE TITLE
'minishift start' continously failing

### ISSUE THREAD

**Issue by richardgreg** [minishift/minishift#3488]
Please I wouldn't come here if I have not run out of options.

I've been trying all sorts of troubleshooting for days but no luck. I do not use any VPN.

Thank you in advance for your time and help.

### General information

  * Minishift version: v1.34.2+83ebaab
  * OS: macOS 
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. minishift start

### Expected
```
OpenShift server started.
   The server is accessible via web console at:
       https://192.168.99.128:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin
```
### Actual
```
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Downloading OpenShift binary 'oc' version 'v3.11.0'
 53.27 MiB / 53.27 MiB [================================================================] 100.00% 0s-- Downloading OpenShift v3.11.0 checksums ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    1
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-centos-iso/releases/download/v1.16.0/minishift-centos7.iso'
 370.00 MiB / 370.00 MiB [==============================================================] 100.00% 0s
-- Starting Minishift VM ............................. OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
-- Writing current configuration for static assignment of IP address ... OK
   Importing 'openshift/origin-control-plane:v3.11.0'  CACHE MISS
   Importing 'openshift/origin-docker-registry:v3.11.0'  CACHE MISS
   Importing 'openshift/origin-haproxy-router:v3.11.0'  CACHE MISS
-- OpenShift cluster will be configured with ...
   Version: v3.11.0
-- Pulling the OpenShift Container Image ............................................... OK
-- Copying oc binary from the OpenShift container image to VM ... OK
-- Starting OpenShift cluster ................................................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --base-dir /var/lib/minishift/base --image 'openshift/origin-${component}:v3.11.0' --public-hostname 192.168.99.122 --routing-suffix 192.168.99.122.nip.io
err     : exit status 2
output  : Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Pulling image openshift/origin-cli:v3.11.0
E1018 16:30:33.659503    2544 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-cli:v3.11.0 anonymously
Image pull complete
Pulling image openshift/origin-node:v3.11.0
E1018 16:30:41.261750    2544 helper.go:173] Reading docker config from /home/docker/.docker/config.json failed: open /home/docker/.docker/config.json: no such file or directory, will attempt to pull image docker.io/openshift/origin-node:v3.11.0 anonymously
Pulled 5/6 layers, 84% complete
Pulled 6/6 layers, 100% complete
Extracting
Image pull complete
Checking type of volume mount ...
Determining server IP ...
Using public hostname IP 192.168.99.122 as the host IP
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.11.0 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.11.0 ...
I1018 16:31:30.993168    2544 config.go:40] Running "create-master-config"
I1018 16:31:37.436271    2544 config.go:46] Running "create-node-config"
I1018 16:31:38.592004    2544 flags.go:30] Running "create-kubelet-flags"
I1018 16:31:39.039370    2544 run_kubelet.go:49] Running "start-kubelet"
I1018 16:31:39.257008    2544 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I1018 16:33:31.748240    2544 interface.go:26] Installing "kube-proxy" ...
I1018 16:33:31.748349    2544 interface.go:26] Installing "kube-dns" ...
I1018 16:33:31.748363    2544 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I1018 16:33:31.748372    2544 interface.go:26] Installing "openshift-apiserver" ...
I1018 16:33:31.844560    2544 apply_template.go:81] Installing "kube-proxy"
I1018 16:33:31.846965    2544 apply_template.go:81] Installing "kube-dns"
I1018 16:33:31.850489    2544 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1018 16:33:31.851058    2544 apply_template.go:81] Installing "openshift-apiserver"
I1018 16:33:50.582528    2544 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
I1018 16:38:03.174328    2544 run_self_hosted.go:242] openshift-apiserver available
I1018 16:38:03.265994    2544 interface.go:26] Installing "openshift-controller-manager" ...
I1018 16:38:03.266133    2544 apply_template.go:81] Installing "openshift-controller-manager"
I1018 16:38:21.392708    2544 interface.go:41] Finished installing "openshift-controller-manager"
Adding default OAuthClient redirect URIs ...
Adding router ...
Adding persistent-volumes ...
Adding registry ...
Adding sample-templates ...
Adding web-console ...
Adding centos-imagestreams ...
I1018 16:38:22.415609    2544 interface.go:26] Installing "openshift-router" ...
I1018 16:38:22.415628    2544 interface.go:26] Installing "persistent-volumes" ...
I1018 16:38:22.415639    2544 interface.go:26] Installing "openshift-image-registry" ...
I1018 16:38:22.415648    2544 interface.go:26] Installing "sample-templates" ...
I1018 16:38:22.415660    2544 interface.go:26] Installing "openshift-web-console-operator" ...
I1018 16:38:22.415670    2544 interface.go:26] Installing "centos-imagestreams" ...
I1018 16:38:22.475014    2544 interface.go:26] Installing "sample-templates/nodejs quickstart" ...
I1018 16:38:22.475040    2544 interface.go:26] Installing "sample-templates/rails quickstart" ...
I1018 16:38:22.475049    2544 interface.go:26] Installing "sample-templates/jenkins pipeline ephemeral" ...
I1018 16:38:22.475058    2544 interface.go:26] Installing "sample-templates/postgresql" ...
I1018 16:38:22.475066    2544 interface.go:26] Installing "sample-templates/dancer quickstart" ...
I1018 16:38:22.475075    2544 interface.go:26] Installing "sample-templates/django quickstart" ...
I1018 16:38:22.475082    2544 interface.go:26] Installing "sample-templates/cakephp quickstart" ...
I1018 16:38:22.475090    2544 interface.go:26] Installing "sample-templates/sample pipeline" ...
I1018 16:38:22.475103    2544 interface.go:26] Installing "sample-templates/mongodb" ...
I1018 16:38:22.475111    2544 interface.go:26] Installing "sample-templates/mariadb" ...
I1018 16:38:22.475228    2544 interface.go:26] Installing "sample-templates/mysql" ...
I1018 16:38:22.475582    2544 apply_list.go:67] Installing "sample-templates/mysql"
I1018 16:38:22.476203    2544 apply_template.go:81] Installing "openshift-web-console-operator"
I1018 16:38:22.476631    2544 apply_list.go:67] Installing "sample-templates/nodejs quickstart"
I1018 16:38:22.476782    2544 apply_list.go:67] Installing "sample-templates/rails quickstart"
I1018 16:38:22.476918    2544 apply_list.go:67] Installing "sample-templates/jenkins pipeline ephemeral"
I1018 16:38:22.477235    2544 apply_list.go:67] Installing "sample-templates/postgresql"
I1018 16:38:22.477389    2544 apply_list.go:67] Installing "sample-templates/dancer quickstart"
I1018 16:38:22.477520    2544 apply_list.go:67] Installing "sample-templates/django quickstart"
I1018 16:38:22.477744    2544 apply_list.go:67] Installing "sample-templates/cakephp quickstart"
I1018 16:38:22.477880    2544 apply_list.go:67] Installing "sample-templates/sample pipeline"
I1018 16:38:22.478004    2544 apply_list.go:67] Installing "sample-templates/mongodb"
I1018 16:38:22.478128    2544 apply_list.go:67] Installing "sample-templates/mariadb"
I1018 16:38:22.478386    2544 apply_list.go:67] Installing "centos-imagestreams"
E1018 16:40:31.191733    2544 interface.go:34] Failed to install "openshift-image-registry": could not run "openshift-image-registry": rc=1
panic: Get https://192.168.99.122:8443/apis/apiregistration.k8s.io/v1beta1/apiservices?watch=true: dial tcp 192.168.99.122:8443: connect: connection refused

goroutine 1478 [running]:
github.com/openshift/origin/pkg/oc/clusterup.watchAPIServices(0x30cce80, 0xc4208be6a0)
   /tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/run_self_hosted.go:591 +0x5f6
created by github.com/openshift/origin/pkg/oc/clusterup.(*ClusterUpConfig).StartSelfHosted
   /tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/run_self_hosted.go:244 +0xdad
```
### Logs
https://gist.github.com/richardgreg/fe8bd7e393ac0d496dcfba7a0a9054c5

**Comment by richardgreg** [comment]
Update

So I changed the network settings in Virtualbox to `Bridged Adaptor`. Now when I start up minishift I get a different error
```
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'virtualbox' is supported on this platform ... OK
-- Checking if VirtualBox is installed ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'virtualbox' hypervisor ...
-- Starting Minishift VM .................................................................... FAIL E1020 11:45:08.976144    6263 start.go:494] Error starting the VM: Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
Error starting the VM: Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```
