### ISSUE TITLE
Unauthenticated proxy not working in Minishift

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift#452]
```
hudson@cdkqe-agajdosi-proxy-test ~]$ minishift start --http-proxy http://proxy.redhat.com:3128 --username foo --password bar

panic: runtime error: index out of range

 

goroutine 1 [running]:

panic(0x162e7a0, 0xc420010100)

	/usr/lib/golang/src/runtime/panic.go:500 +0x1a1

github.com/minishift/minishift/cmd/minishift/cmd.SetRegistrationProxyParameters()

	/home/jenkins/work/src/github.com/minishift/minishift/cmd/minishift/cmd/start.go:255 +0x1c2

github.com/minishift/minishift/cmd/minishift/cmd.runStart(0x19de2d60, 0xc42005a480, 0x0, 0x6)

	/home/jenkins/work/src/github.com/minishift/minishift/cmd/minishift/cmd/start.go:129 +0x2e7

github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).execute(0x19de2d60, 0xc42005a3c0, 0x6, 0x6, 0x19de2d60, 0xc42005a3c0)

	/home/jenkins/work/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:650 +0x443

github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19de22c0, 0x0, 0x0, 0x0)

	/home/jenkins/work/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:737 +0x367

github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).Execute(0x19de22c0, 0xc420313600, 0xc4203134e0)

	/home/jenkins/work/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:695 +0x2b

github.com/minishift/minishift/cmd/minishift/cmd.Execute()

	/home/jenkins/work/src/github.com/minishift/minishift/cmd/minishift/cmd/root.go:103 +0x2d

main.main()

	/home/jenkins/work/src/github.com/minishift/minishift/cmd/minishift/main.go:24 +0x14
```

**Comment by hferentschik** [comment]
Merged via pull request #453
