### ISSUE TITLE
Failed starting openshif v1.5.0-rc.0 with minishift-centos7.iso v1.0.0-rc.3

### ISSUE THREAD

**Issue by tiraboschi** [minishift/minishift#592]
I was playing with openshif v1.5.0-rc.0 and it was fine with boot2docker; than I tried moving to minishift-centos7 but started the VM just once and than it started hanging on the boot process.

Not sure if it's reproducible and how.

```
[stirabos@t440s ovirt-containers] $ minishift start --memory 4096 --iso-url=https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-rc.3/minishift-centos7.iso --openshift-version=v1.5.0-rc.0 --show-libmachine-logs  --v=5
Starting local OpenShift cluster using 'kvm' hypervisor...
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:37761
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG | 
(minishift) DBG | goroutine 22 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a160)
(minishift) DBG | 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc8200161c0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc8200e7ee0, 0xe0d430, 0xc82016e8c8, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc82016aef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc82016aef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc820019bc0, 0xc820019980, 0xc82016e060, 0xc82001b780, 0xc82015a640, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc82016e8c8, ...)
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
E0322 15:15:23.896407    7979 start.go:150] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:34531
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG | 
(minishift) DBG | goroutine 6 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a160)
(minishift) DBG | 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc8201560e0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc82010ba00, 0xe0d430, 0xc82000a9f8, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc82003bef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc82003bef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc820071a80, 0xc820071840, 0xc82000a190, 0xc8200cf680, 0xc820010a80, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc82000a9f8, ...)
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
E0322 15:15:23.930893    7979 start.go:150] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
Found binary path at /usr/local/bin/docker-machine-driver-kvm
Launching plugin server for driver kvm
Plugin server listening at address 127.0.0.1:42891
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minishift) Calling .GetState
(minishift) DBG | Getting current state...
(minishift) DBG | Fetching VM...
(minishift) Failed to fetch machine
(minishift) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(minishift) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x4d7167]
(minishift) DBG | 
(minishift) DBG | goroutine 22 [running]:
(minishift) DBG | panic(0x8c54a0, 0xc82000a160)
(minishift) DBG | 	/usr/local/go/src/runtime/panic.go:464 +0x3e6
(minishift) DBG | github.com/alexzorin/libvirt-go.(*VirDomain).GetState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/alexzorin/libvirt-go/domain.go:192 +0x87
(minishift) DBG | github.com/dhiltgen/docker-machine-kvm.(*Driver).GetState(0xc8200161c0, 0x0, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/dhiltgen/docker-machine-kvm/kvm.go:450 +0x70
(minishift) DBG | github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc8200e7ee0, 0xe0d430, 0xc82016e8c8, 0x0, 0x0)
(minishift) DBG | 	/home/daniel/go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:191 +0x45
(minishift) DBG | reflect.Value.call(0x8858a0, 0x93fe88, 0x13, 0x959cd0, 0x4, 0xc82016aef8, 0x3, 0x3, 0x0, 0x0, ...)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:435 +0x120d
(minishift) DBG | reflect.Value.Call(0x8858a0, 0x93fe88, 0x13, 0xc82016aef8, 0x3, 0x3, 0x0, 0x0, 0x0)
(minishift) DBG | 	/usr/local/go/src/reflect/value.go:303 +0xb1
(minishift) DBG | net/rpc.(*service).call(0xc820019bc0, 0xc820019980, 0xc82016e060, 0xc82001b780, 0xc82015a640, 0x7e14a0, 0xe0d430, 0x16, 0x89fca0, 0xc82016e8c8, ...)
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:383 +0x1c2
(minishift) DBG | created by net/rpc.(*Server).ServeCodec
(minishift) DBG | 	/usr/local/go/src/net/rpc/server.go:477 +0x49d
E0322 15:15:23.960016    7979 start.go:150] Error starting the VM: Error getting the state for host: unexpected EOF. Retrying.
E0322 15:15:23.960978    7979 start.go:156] Error starting the VM:  Error getting the state for host: unexpected EOF
Error getting the state for host: unexpected EOF
Error getting the state for host: unexpected EOF
```

**Comment by LalatenduMohanty** [comment]
I could not reproduce this on Fedora 25 + KVM
```
$ minishift start --iso-url file:///home/lmohanty/Downloads/minishift-centos7.iso --openshift-version=v1.5.0-rc.0

Starting local OpenShift cluster using 'kvm' hypervisor...
Provisioning OpenShift via '/home/lmohanty/.minishift/cache/oc/v1.5.0-rc.0/oc [cluster up --use-existing-config --host-config-dir /var/lib/minishift/openshift.local.config --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --routing-suffix 192.168.42.151.nip.io]'
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for openshift/origin:v1.5.0-rc.0 image ... 
   Pulling image openshift/origin:v1.5.0-rc.0
   Pulled 0/3 layers, 3% complete
   Pulled 1/3 layers, 52% complete
   Pulled 1/3 layers, 64% complete
   Pulled 1/3 layers, 66% complete
   Pulled 1/3 layers, 68% complete
   Pulled 1/3 layers, 70% complete
   Pulled 1/3 layers, 73% complete
   Pulled 1/3 layers, 75% complete
   Pulled 1/3 layers, 80% complete
   Pulled 2/3 layers, 81% complete
   Pulled 2/3 layers, 83% complete
   Pulled 2/3 layers, 85% complete
   Pulled 2/3 layers, 91% complete
   Pulled 2/3 layers, 92% complete
   Pulled 2/3 layers, 93% complete
   Pulled 2/3 layers, 95% complete
   Pulled 2/3 layers, 96% complete
   Pulled 2/3 layers, 97% complete
   Pulled 2/3 layers, 98% complete
   Pulled 2/3 layers, 99% complete
   Pulled 2/3 layers, 100% complete
   Pulled 3/3 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using nsenter mounter for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using 192.168.42.151 as the server IP
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... OK
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Login to server ... OK
-- Creating initial project "myproject" ... OK
-- Removing temporary directory ... OK
-- Checking container networking ... OK
-- Server Information ... 
   OpenShift server started.
   The server is accessible via web console at:
       https://192.168.42.151:8443

   You are logged in as:
       User:     developer
       Password: developer

   To login as administrator:
       oc login -u system:admin

```

**Comment by gbraad** [comment]
Likely the KVM environment is not as expected.

```
$ sudo virsh destroy minishift
$ sudo virsh undefine minishift
$ systemctl restart libvirtd
```

**Comment by tiraboschi** [comment]
After a reboot of my physical host I was able to start mini-shift VM again, probably something got messed up on my env
